### ISSUE TITLE
make rebuild error: " LookupError: App 'auth' doesn't have a 'demouser' model."

### ISSUE THREAD

**Issue by jcda** [aellerton/demo-allauth-bootstrap#10]
Help ! 
I am trying to simply the project throuh a Django 1.8 environment using Python 3.4 . I tried with 1.7 too 
I tried firstly on a Mac, then on a linux computer with the same output.

The "make configure" is going fine but the "make rebuild" is giving my a terrible output. (copied/pasted here after a blank setup with no facebook setup nor google )

<SNIP>-----------------------------------------------------------
/1.8-projects/demo-allauth-bootstrap$ make rebuild
rm -f db.sqlite3
python manage.py syncdb --noinput
Traceback (most recent call last):
  File "/home/jcda/django/1.8-projects/lib/python3.4/site-packages/django/apps/config.py", line 159, in get_model
    return self.models[model_name.lower()]
KeyError: 'demouser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jcda/django/1.8-projects/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/jcda/django/1.8-projects/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jcda/django/1.8-projects/lib/python3.4/site-packages/django/core/management/base.py", line 390, in run$from_argv
    self.execute(*args, **cmd_options)
  File "/home/jcda/django/1.8-projects/lib/python3.4/site-packages/django/core/management/base.py", line 440, in exe$ute
    self.check()
  File "/home/jcda/django/1.8-projects/lib/python3.4/site-packages/django/core/management/base.py", line 478, in che$k
    include_deployment_checks=include_deployment_checks,
  File "/home/jcda/django/1.8-projects/lib/python3.4/site-packages/django/core/checks/registry.py", line 72, in run_$hecks
    new_errors = check(app_configs=app_configs)
  File "/home/jcda/django/1.8-projects/lib/python3.4/site-packages/django/contrib/auth/checks.py", line 12, in check$user_model
    cls = apps.get_model(settings.AUTH_USER_MODEL)
  File "/home/jcda/django/1.8-projects/lib/python3.4/site-packages/django/apps/registry.py", line 202, in get_model
    return self.get_app_config(app_label).get_model(model_name.lower())
  File "/home/jcda/django/1.8-projects/lib/python3.4/site-packages/django/apps/config.py", line 162, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'auth' doesn't have a 'demouser' model.
make: *** [syncdb] Error 1
<SNIP>-----------------------------------------------------------

Has anyone had the same error ?
How did you solve it ?
Am I missing something ?
Thanks in advance for any help/pointer .
JC

**Comment by aellerton** [comment]
Please try again after doing a git pull of the latest which has the patch to work with Django 1.8 from @gson (thanks!).

**Comment by jcda** [comment]
Thanks @aellerton and @gsong , it runs smoothly
by the way, there is this warning:
/Users/jcda/roo-django1.8/lib/python3.4/site-packages/django/core/management/commands/syncdb.py:24: RemovedInDjango19Warning: The syncdb command will be removed in Django 1.9
  warnings.warn("The syncdb command will be removed in Django 1.9", RemovedInDjango19Warning)

I guess this will have to be change to "./manage.py migrate" in a next release (seeing the django roadmap, there is still some time for that though )
