### ISSUE TITLE
LookupError: App 'auth' doesn't have a 'demouser' model

### ISSUE THREAD

**Issue by marcelh89** [aellerton/demo-allauth-bootstrap#11]
When i change the requirements.txt to use django 1.7 or 1.8 with python3
the make rebuild (especially the python manage.py syncdb --noinput
) fails with the following Exception:

LookupError: App 'auth' doesn't have a 'demouser' model

Traceback (most recent call last):
  File "/home/marcman/git/demo-allauth-bootstrap/allauth/lib/python3.4/site-packages/django/apps/config.py", line 163, in get_model
    return self.models[model_name.lower()]
KeyError: 'demouser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/marcman/git/demo-allauth-bootstrap/allauth/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/marcman/git/demo-allauth-bootstrap/allauth/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/marcman/git/demo-allauth-bootstrap/allauth/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/marcman/git/demo-allauth-bootstrap/allauth/lib/python3.4/site-packages/django/core/management/base.py", line 337, in execute
    self.check()
  File "/home/marcman/git/demo-allauth-bootstrap/allauth/lib/python3.4/site-packages/django/core/management/base.py", line 371, in check
    all_issues = checks.run_checks(app_configs=app_configs, tags=tags)
  File "/home/marcman/git/demo-allauth-bootstrap/allauth/lib/python3.4/site-packages/django/core/checks/registry.py", line 59, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/marcman/git/demo-allauth-bootstrap/allauth/lib/python3.4/site-packages/django/contrib/auth/checks.py", line 12, in check_user_model
    cls = apps.get_model(settings.AUTH_USER_MODEL)
  File "/home/marcman/git/demo-allauth-bootstrap/allauth/lib/python3.4/site-packages/django/apps/registry.py", line 202, in get_model
    return self.get_app_config(app_label).get_model(model_name.lower())
  File "/home/marcman/git/demo-allauth-bootstrap/allauth/lib/python3.4/site-packages/django/apps/config.py", line 166, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'auth' doesn't have a 'demouser' model.
make: *** [syncdb] Fehler 1

**Comment by aellerton** [comment]
Are you definitely using the latest from github? requirements.txt lists django 1.8.1 and worked fine last time I checked.

**Comment by marcelh89** [comment]
sorry there was an error in my git settings not updating to the last version, it works nowm thank you

**Comment by aellerton** [comment]
All good, thanks.
